# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='movie',
            new_name='movie_role',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='person',
            new_name='person_role',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='movies.Person'),
        ),
    ]
